available_objects = [
    {
        "title": "Đài thờ Trà Kiệu",
        "content": "Niên đại: Thế kỷ VII - VIII\nXuất xứ: Trà Kiệu, Quảng Nam\nKí hiệu: BTC 95\nChất liệu: Sa thạch\n\nNguồn gốc:\nĐài thờ Trà Kiệu mang ký hiệu 22.2, được trưng bày tại trung tâm của phòng Trà Kiệu ở Bảo tàng Điêu khắc Chăm. Các bộ phận của bảo vật này đã được sưu tầm từ Trà Kiệu (nay thuộc xã Duy Sơn, huyện Duy Xuyên, tỉnh Quảng Nam) và đưa về Đà Nẵng vào tháng 12 năm 1891 và tháng 1 năm 1892.\n\nMô tả:\nĐài thờ Trà Kiệu được làm bằng đá sa thạch, có kích thước cao 128cm, dài và rộng 190cm, có niên đại từ thế kỷ VII-VIII. Đài thờ gồm hai phần: phần khối tròn ở trên và khối vuông ở dưới; 4 cạnh được chạm khắc các cảnh sinh hoạt và lễ tôn thờ của các vị thần.\n\nCâu chuyện:\nTheo nghiên cứu của Trần Kỳ Phương, đài thờ này thể hiện câu chuyện về đám cưới Sita-Rama trong trường ca Ramayana.\n\nÝ nghĩa:\nĐài thờ được đưa về bảo tàng năm 1901 và hiện là một trong sáu bảo vật quốc gia tại Bảo tàng Điêu khắc Chăm Đà Nẵng.",
    },
    {
        "title": "Đản sinh Brahma",
        "content": "Đản sinh Brahma\nNiên đại: Thế kỷ VII - VIII\nXuất xứ: Mỹ Sơn, Quảng Nam\nChất liệu: Sa thạch\n\nNguồn gốc\nBức chạm khắc trang trí trên vòm cửa của tháp Mỹ Sơn E1, được đưa về bảo tàng năm 1935.\n\nNội dung\nBức chạm minh họa thần Visnu nằm trên biển vũ trụ, được nâng đỡ bởi rắn thần Shesha 7 đầu. Từ rốn Visnu mọc lên một hoa sen, trên đó thần Brahma ra đời trong tư thế thiền định. Phía chân thần Visnu là một vị đạo sĩ đang chúc phúc. Hai đầu bức phù điêu là hai chim thần Garuda mình người chân chim.\n\nÝ nghĩa\nTác phẩm phản ánh tôn giáo, tín ngưỡng của người Chăm và mối liên hệ giữa văn hóa Ấn Độ và văn hóa Chăm.\n\nTrưng bày\nPhù điêu được trưng bày tại bảo tàng, giúp du khách hiểu rõ hơn về lịch sử và văn hóa Chăm.",
    },
    {
        "title": "Phù điêu Apsara (Trà Kiệu)",
        "content": "Phù điêu Apsara (Trà Kiệu)\nChất liệu: Sa thạch\nNiên đại: Khoảng thế kỷ X-XI\n\nNguồn gốc\nHiện diện tại các di tích Champa như Mỹ Sơn, Đồng Dương, Trà Kiệu (Quảng Nam). Công nhận bảo vật Quốc gia năm 2024.\n\nNội dung\nMiêu tả hai vũ nữ Apsara trong tư thế múa (tribhaṅga) với trang phục và trang sức tinh xảo. Phù điêu còn có hình ảnh các nhạc công Gandharva đang chơi nhạc cụ dây (Tuila).\n\nGiá trị văn hóa và nghệ thuật\nNguồn cảm hứng cho nghệ thuật biểu diễn\nBiểu tượng của vẻ đẹp thuần khiết và tính biểu cảm\nXuất hiện trong nhiều lễ hội và sự kiện văn hóa\n\nGiá trị lịch sử\nKiệt tác điêu khắc Chăm, phản ánh nghệ thuật tôn giáo Champa qua nhiều giai đoạn lịch sử.\n\nThông tin thêm\nApsara trong thần thoại Ấn Độ là những nàng tiên xinh đẹp của thiên giới. Vũ điệu Apsara thường thuật lại những câu chuyện thần thoại hoặc tôn giáo.",
    },
    {
        "title": "Tượng Phật Quan Âm 67m tại chùa Linh Ứng",
        "content": "Tượng Phật Quan Âm tại chùa Linh Ứng Bãi Bụt, Đà Nẵng\n\nNguồn gốc và sự ra đời\nKhởi công xây dựng năm 2004\nDựa trên ước nguyện của người dân địa phương\nGắn liền với truyền thuyết về pho tượng Phật trôi dạt vào bờ\n\nQuá trình xây dựng\nKhánh thành năm 2010 sau 6 năm xây dựng\nChiều cao: 67 mét\nĐường kính tòa sen: 35 mét\nThiết kế và thi công phức tạp trên địa hình núi cao\n\nÝ nghĩa tâm linh và văn hóa\nBiểu tượng của lòng từ bi và sự cứu khổ cứu nạn\nĐược tin là bảo vệ ngư dân khi ra khơi\nGóp phần phát triển du lịch văn hóa, tôn giáo của Đà Nẵng",
    },
    {
        "title": "Tượng thần Shiva",
        "content": "Tượng thần Shiva tại Bảo tàng Chăm Đà Nẵng\nChất liệu: Sa thạch\nNiên đại: Thế kỷ VIII\n\nNguồn gốc và phát hiện\nTìm thấy tại tháp C1 năm 1903\nBộ trang sức vàng (1,5kg) tìm thấy ở tháp C7 gần bên\n\nĐặc điểm\nCòn dấu vết lỗ đeo trang sức ở dái tai\nTrang phục: sampot dài đến đầu gối\nKhuôn mặt: lông mày giao nhau, mắt mở lớn, mũi thẳng, môi dày, râu mép thanh tú\nKiểu tóc: jata-mukuta kết lại buông dài đến thái dương\n\nPhong cách nghệ thuật\nThuộc giai đoạn muộn của phong cách Mỹ Sơn E1\nThể hiện phong cách nghệ thuật Chăm tinh xảo, sống động\n\nÝ nghĩa\nPhản ánh sự giao thoa giữa tín ngưỡng Hindu và văn hóa bản địa\nĐóng vai trò quan trọng trong nghi lễ tôn thờ\n\nBảo tàng Chăm Đà Nẵng\nThành lập năm 1915\nNơi lưu giữ và trưng bày nhiều hiện vật văn hóa Chăm",
    },
    {
        "title": "Lồng đèn Hội An",
        "content": "Lồng đèn Hội An là một biểu tượng văn hóa đặc trưng của phố cổ Hội An, một di sản văn hóa thế giới của Việt Nam. Không chỉ là vật dụng chiếu sáng, lồng đèn còn mang giá trị lịch sử, văn hóa và nghệ thuật đặc sắc.\n\nLịch sử\nXuất hiện từ thế kỷ XVI\nẢnh hưởng từ văn hóa Trung Hoa và Nhật Bản\nĐược cải tiến để phù hợp với văn hóa Việt Nam\n\nLoại lồng đèn\nLồng đèn hình tròn: Phổ biến nhất, giống quả bí ngô hoặc hình trụ\n\nVai trò trong đời sống\nSử dụng để thắp sáng và trang trí\nQuan trọng trong nghi lễ tín ngưỡng và lễ hội\n\nSự phát triển và bảo tồn\nLàng nghề truyền thống duy trì sản xuất\nPhát triển mạnh mẽ với sự phát triển du lịch\nTổ chức lễ hội lồng đèn thường xuyên\n\nGiá trị văn hóa và tinh thần\nBiểu tượng của may mắn và hòa bình\nThể hiện sự giao thoa văn hóa\nĐòi hỏi kỹ năng thủ công tinh xảo",
    },
    {
        "title": "Nón lá",
        "content": "Nón lá là biểu tượng truyền thống của Việt Nam, gắn liền với hình ảnh người phụ nữ Việt và văn hóa dân gian.\n\nLịch sử\nCó từ hơn 3.000 năm trước\nXuất hiện trên trống đồng Ngọc Lũ (thế kỷ III TCN)\nPhát triển qua các triều đại phong kiến\n\nĐặc điểm\nHình chóp nhọn, tròn và to\nLàm từ lá cọ, tre nứa\nNhẹ, bền và chống thấm nước\n\nCác loại nón lá\nNón lá Huế: Nổi tiếng với 'nón bài thơ'\nNón lá Nghệ An: Kích thước lớn, nặng hơn\nNón lá Bắc Ninh: Gắn liền với hát quan họ\n\nNghề làm nón lá\nTồn tại ở nhiều địa phương\nLàng nghề nổi tiếng: Phú Cam (Huế), Chuông (Hà Nội)\nQuy trình làm nón tỉ mỉ, đòi hỏi kỹ năng\n\nGiá trị văn hóa\nBiểu tượng của sự dịu dàng, duyên dáng\nXuất hiện trong thơ ca, nhạc họa\n\nVai trò hiện đại\nVẫn được sử dụng rộng rãi ở nông thôn\nXuất hiện trong sự kiện văn hóa, du lịch\nĐược sử dụng trong thời trang hiện đại",
    },
    {
        "title": "Vòng đá mỹ nghệ Non Nước",
        "content": "Làng đá mỹ nghệ Non Nước, Đà Nẵng nổi tiếng với nghề chế tác đá cẩm thạch và các loại đá quý khác thành các sản phẩm mỹ nghệ và trang sức.\n\nĐặc điểm nổi bật\nNguyên liệu: Đá cẩm thạch từ núi Ngũ Hành Sơn và các vùng lân cận\nKỹ thuật điêu khắc: Tinh xảo, kết hợp truyền thống và hiện đại\n\nLịch sử phát triển\nKhởi nguồn từ cuối thế kỷ 17\nPhát triển mạnh vào thế kỷ 18-19 với sự phát triển của đạo Phật\nGiao thoa với phong cách phương Tây trong thời Pháp thuộc\n\nSản phẩm\nĐa dạng: Tượng Phật, linh vật, phù điêu, trang sức\nGiá trị cao về thẩm mỹ và phong thủy\n\nBảo tồn và phát triển\nĐược công nhận là di sản văn hóa phi vật thể\nHỗ trợ truyền dạy nghề cho thế hệ trẻ\nQuảng bá sản phẩm ra thị trường quốc tế\n\nTầm quan trọng\nVăn hóa: Bảo tồn giá trị lịch sử và nghệ thuật\nKinh tế: Đóng góp vào nền kinh tế địa phương\nDu lịch: Điểm đến hấp dẫn của Đà Nẵng",
    },
    {
        "title": "Bánh khô mè Cẩm Lệ",
        "content": "Bánh khô mè Đà Nẵng là đặc sản truyền thống nổi tiếng của miền Trung Việt Nam, đặc biệt là từ làng Cẩm Lệ.\n\nNguyên liệu chính\nGạo nếp\nMè (vừng) rang vàng\nĐường mía hoặc đường thốt nốt\nGừng\n\nLịch sử hình thành\nCó nguồn gốc từ cuối thế kỷ 19, đầu thế kỷ 20\nBan đầu dùng trong dịp lễ tết, cúng giỗ\nDần trở thành món ăn phổ biến\n\nPhát triển làng nghề\nTrung tâm sản xuất: làng Cẩm Lệ\nPhát triển từ quy mô gia đình đến sản xuất lớn\nMở rộng thị trường trong và ngoài nước\n\nNghệ thuật truyền thống\nĐòi hỏi kỹ thuật và sự khéo léo\nBí quyết gia truyền qua nhiều thế hệ\n\nGiá trị kinh tế và văn hóa\nBiểu tượng văn hóa ẩm thực Đà Nẵng\nĐóng góp vào kinh tế địa phương\nTạo việc làm cho lao động địa phương\nĐược công nhận là đặc sản truyền thống cần bảo tồn",
    },
]